name: Tests

on:
  push:
  workflow_dispatch:

env:
  ITEST_ECS_REGION: dummy-region
  ITEST_ECS_NAME: dummy-name
  ITEST_ECS_SECURITY_GROUPS: dummy-sg
  ITEST_ECS_SUBNETS: dummy-subnets

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
        kubernetes:
          - 'v1.24.17'
          - 'v1.25.16'
          - 'v1.26.15'
          - 'v1.27.13'
          - 'v1.28.9'
          - 'v1.29.4'
          - 'v1.30.0'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.33.0'
          kubernetes version:  ${{ matrix.kubernetes }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          container runtime: containerd
          driver: docker
      - name: Setup Docker
        run: sudo apt-get -qq -y install conntrack socat ; nohup socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock &
      - name: Setup Docker Swarm
        run: docker swarm init
      - name: Pull Image
        run: docker pull openanalytics/shinyproxy-integration-test-app
      - name: Run redis
        run: docker run -d -p 6379:6379 redis
      - name: Build with Maven
        run: mvn -B -U clean install -DskipTests
      - name: Run Tests
        run:  mvn -B test

  dependency:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run Dependency Check
        run: mvn -B -Powasp-dependency-check verify -DskipTests
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
